* Simple vending machine application for practicing MVC
** The purpose of this repository
   This repository contains the bare bones of an application for
   practicing model-view-controller (MVC) architecture.

** Installation in IDEA
   To install the application in IDEA, do the following:
   1. Clone the repository.
   2. Right click on class =Main=.
   3. Select =Run Main.main()=
   You are now able to make changes to the project and run it again.

** Alternative installation from command line
   1. Clone repository.
   2. Inside repo, run =ant= to build the app.
   3. Run app with
      #+begin_src sh
        java -jar build/jar/Main.jar
      #+end_src
   
** Java =enum=
   In this application, data type =Product= is a Java =enum=, which
   allows you to create a data type with a finite number of possible
   values (\ldquo{}subtypes\rdquo). In this case, the possible values
   of =Product= are initially =Beverage= and =Apple=. Thus, you can
   set, for example
   #+begin_src java :exports code
   Product product = Product.Apple;
   #+end_src
   or evaluate an expression such as
   #+begin_src java :exports code
     if (product == Product.Apple)
       ;
   #+end_src
   Furthermore, data type created with =enum= has similar properties
   as a class in the sense that it can have fields and methods. For
   example, =Product= has a field =priceCents=, an associated getter
   function, and a constructor =Product(int)= which sets the price of
   a product. When identifier =Apple= is declared inside =Product= its
   price is set (take a look at the file).

** License
   Copyright (C) 2020 Jarmo Hurri

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
